In [1]:
import xarray as xr
import numpy as np
import pandas as pd
from scipy import stats

In [9]:
a = 5
print(type(a),a)
a = 5.0
print(type(a),a)
a = np.array(5)
print(type(a),a)
a = '5'
print(type(a),a)
a = 'correlation'
print(type(a),a)

<class 'int'> 5
<class 'float'> 5.0
<class 'numpy.ndarray'> 5
<class 'str'> 5
<class 'str'> correlation


In [16]:
# convert a number to a string
a = 10.0
b = str(a)
print('data type of a:',type(a),'value of a:',a)
print('data type of b:',type(b),'value of b:',b)

data type of a: <class 'float'> value of a: 10.0
data type of b: <class 'str'> value of b: 10.0


### Convert a number to a string and format the string
### f"{a:.2f}": The a:.2f inside the curly braces is a format specifier.
### : indicates the start of the format specifier.
### .2 specifies that we want to keep two decimal places.
### f indicates that the value being formatted is a floating-point number.

In [21]:
# convert a number to a string with defined format
a = np.pi
print(type(a),a)
# method 1
b = f"{a:.2f}"
print(type(b),b)
b = f"{a:.3f}"
print(type(b),b)
b = f"{a:.10f}"
print(type(b),b)
# method 2
b = "{:.2f}".format(a)
print(type(b),b)
b = "{:.10f}".format(a)
print(type(b),b)
# method 3
b = "%.2f" % a   # % marks the start of the formatting
print(type(b),b)
b = "%.10f" % a
print(type(b),b)

<class 'float'> 3.141592653589793
<class 'str'> 3.14
<class 'str'> 3.142
<class 'str'> 3.1415926536
<class 'str'> 3.14
<class 'str'> 3.1415926536
<class 'str'> 3.14
<class 'str'> 3.1415926536


In [27]:
# connect two strings
a = 'correlation'+'='
print(a)
# connect strings and numbers
r_xy = 0.9988
a = 'correlation='+str(r_xy)
print(a)
a = 'correlation'+'='+str(r_xy)
print(a)

correlation=
correlation=0.9988
correlation=0.9988


<span style="font-size: 24px; color: green; font-weight: bold;">Exercise</span>
### define a string variable <span style="font-size: 24px; color: red; font-weight: bold;">text</span> as "r_xy = 0.99"
### define a string variable <span style="font-size: 24px; color: red; font-weight: bold;">text</span> as "r_xy is 0.99 and it indicates strong positive correlation"

## for loop
### print number 0 to 10

In [29]:
for i in range(11):
    print(i)

0
1
2
3
4
5
6
7
8
9
10


In [33]:
a = np.arange(11)
for i in a:
    print(i)

0
1
2
3
4
5
6
7
8
9
10


### print each element in an array

In [37]:
b = np.arange(11)*2
print(b)
for i in range(11):
    print(b[i])

[ 0  2  4  6  8 10 12 14 16 18 20]
0
2
4
6
8
10
12
14
16
18
20


<span style="font-size: 24px; color: green; font-weight: bold;">Exercise</span>
### 1. print index of 0 to 10 and the corresponding number of the array <span style="font-size: 24px; color: red; font-weight: bold;">b</span> using for loop

### 2. Write a program that calculates the sum of all numbers from 1 to 10.

In [40]:
b = np.arange(11)*2
print(b)

[ 0  2  4  6  8 10 12 14 16 18 20]


## if statement

In [41]:
a = 30
b = 200
if b > a:
    print("b is greater than a")

b is greater than a


In [42]:
a = 30
b = 200
if b < a:
    print("b is smaller than a")
else:
    print("b is not smaller than a")

b is not smaller than a


In [43]:
a = 200
b = 200
if b == a:
    print("b is equal to a")

b is equal to a


In [44]:
a = 30
b = 200
if b != a:
    print("b is not equal to a")

b is not equal to a


### variab a = np.arange(10)*2
### find elements in variable <span style="font-size: 24px; color: red; font-weight: bold;">a</span> that are larger than 10

In [52]:
a = np.arange(10)*2
print(a)
b = np.where(a>10)
# b is the indexing of elements in a that corresponds to values larger than 10
print(b) 
# print the elements in a that are larger than 10
print(a[b])

[ 0  2  4  6  8 10 12 14 16 18]
(array([6, 7, 8, 9]),)
[12 14 16 18]


## finding the remainder of a division
### (%): This operator returns the remainder directly.

In [5]:
a = 10
b = 2
print(a % b)

a = 10
b = 3
print(a % b)

0
1


<span style="font-size: 24px; color: green; font-weight: bold;">Exercise</span>
### 1. find elements in variable <span style="font-size: 24px; color: red; font-weight: bold;">a</span>, a = np.array([0,10,10,10,0,0,0,0,10]). Print the indexing in a where values are not equal to 10. Print the elements in a where they are not equal to 10.
### 2. Iterate through the elements in variable <span style="font-size: 24px; color: red; font-weight: bold;">a</span>, a=np.arange(100)+1. If a number is even, print "even" and the number. If a number is odd, print "odd" and the number.