In [2]:
# import library
import numpy as np

In [4]:
a = np.array([1,17,-3,2,16],float)
print(a)
print(a[0])
print(a[1])
print(a[0:2])
print(a[0:3])
print(a[1:3])
print(a[:])
print(a.ndim)
print(a.shape)

[ 1. 17. -3.  2. 16.]
1.0
17.0
[ 1. 17.]
[ 1. 17. -3.]
[17. -3.]
[ 1. 17. -3.  2. 16.]
1
(5,)


In [5]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.ndim)
print(a.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [6]:
a = np.empty(6)
print(a)

[4.68687511e-310 0.00000000e+000 6.91871086e-310 6.91871084e-310
 4.68589736e-310 6.91871086e-310]


In [7]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [8]:
x = np.arange(1,10.5,0.5)
print(x)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


In [9]:
x = np.linspace(0,-3,11)
print(x)

[ 0.  -0.3 -0.6 -0.9 -1.2 -1.5 -1.8 -2.1 -2.4 -2.7 -3. ]


In [10]:
m = np.empty(shape=[2,3],dtype=float)
print(m)

[[4.68687511e-310 0.00000000e+000 6.91871086e-310]
 [6.91871084e-310 4.68589736e-310 6.91871086e-310]]


In [11]:
m1 = np.empty(shape=[5,1],dtype=float)
print(m1)

[[4.68687511e-310]
 [6.91871086e-310]
 [6.91871084e-310]
 [4.68589736e-310]
 [6.91871086e-310]]


In [3]:
data = np.load('/nfs/spare11/env315/data/temp_Albany.npy')
print(data)

[  0.02886963   2.986267     0.5474243    1.1485596    1.5075989
   0.0715332   -1.6253967   -2.438263    -3.4477844   -1.8928528
  -1.143158     0.5550537    0.77407837   3.016632     3.258728
   4.287781     2.8318787    2.6882324   -0.08886719   0.10916138
  -3.7025146    2.7068787   -3.354309    -8.784943    -5.8197327
  -1.8783875   -0.91360474  -4.2061462  -11.422974   -11.247101
  -8.903534    -5.5658875   -0.5288086   -1.1286926   -0.72335815
   3.3402405    1.295044    -0.8993225   -6.990631    -4.8329163
  -4.6866455   -4.907776    -8.733215    -7.266327    -3.5367126
  -3.385376     2.238556    -4.747467    -5.6511536   -4.0522766
  -2.9458923   -5.4247437   -2.1228943    2.0964355    4.7809143
   5.106659    -0.348114     2.3112793    4.4199524    5.1304016
  -6.610443    -1.085846     2.3092957   -5.5950317   -4.4308777
  -5.033203    -4.245636     5.2790833    6.4423523    9.763611
  12.561157     2.5680237    2.5767517   -5.8833313   -3.4980774
   1.878479     5.1824036 

In [5]:
data = np.loadtxt('/nfs/spare11/env315/data/temp_Albany.txt')
print(data.shape)

(365,)


In [6]:
data = np.loadtxt('/nfs/spare11/env315/data/temp_Albany.csv', delimiter=',')
print(data.shape)

(365,)


In [2]:
from netCDF4 import Dataset

In [25]:
DIR = '/nfs/spare11/env315/data/'
filename = DIR+'era5_an_t2m_reg025_6h_202512.nc'
data = Dataset(filename,mode='r')
print(data.variables.keys())
t2m = data.variables['t2m'][:].data
data.close()
print(t2m.data.shape)

dict_keys(['number', 'valid_time', 'latitude', 'longitude', 'expver', 't2m'])
(124, 721, 1440)
